#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3 effective-5.10 (swiftlang-6.3.0.123.5 clang-2100.0.123.102)
#ifndef VIETMAPTRACKINGSDK_SWIFT_H
#define VIETMAPTRACKINGSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="VietmapTrackingSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreLocation;
@import Foundation;
@import ObjectiveC;
@import _LocationEssentials;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="VietmapTrackingSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class CLLocation;
@class NSString;
SWIFT_CLASS("_TtC18VietmapTrackingSDK23EnhancedLocationManager")
@interface EnhancedLocationManager : NSObject
@property (nonatomic, copy) void (^ _Nullable onLocationUpdate)(CLLocation * _Nonnull, NSString * _Nonnull, NSString * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onLocationError)(NSString * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onAuthorizationChanged)(CLAuthorizationStatus);
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)startTrackingWithHighAccuracyMode:(BOOL)highAccuracyMode SWIFT_AVAILABILITY(ios,introduced=14.0);
- (void)stopTracking;
- (void)requestLocationPermissions SWIFT_AVAILABILITY(ios,introduced=14.0);
- (BOOL)isTracking SWIFT_WARN_UNUSED_RESULT;
- (CLLocation * _Nullable)getLastKnownLocation SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getLocationServicesStatus SWIFT_WARN_UNUSED_RESULT SWIFT_AVAILABILITY(ios,introduced=14.0);
- (void)requestFullAccuracy;
- (void)setCustomAccuracy:(CLLocationAccuracy)accuracy distanceFilter:(CLLocationDistance)distanceFilter;
- (void)enableBackgroundLocationUpdates:(BOOL)enable SWIFT_AVAILABILITY(ios,introduced=14.0);
@end

@class CLLocationManager;
@interface EnhancedLocationManager (SWIFT_EXTENSION(VietmapTrackingSDK)) <CLLocationManagerDelegate>
- (void)locationManager:(CLLocationManager * _Nonnull)manager didUpdateLocations:(NSArray<CLLocation *> * _Nonnull)locations;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didFailWithError:(NSError * _Nonnull)error;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didChangeAuthorizationStatus:(CLAuthorizationStatus)status;
- (void)locationManagerDidChangeAuthorization:(CLLocationManager * _Nonnull)manager SWIFT_AVAILABILITY(ios,introduced=14.0);
@end

SWIFT_CLASS("_TtC18VietmapTrackingSDK14TrackingConfig")
@interface TrackingConfig : NSObject
@property (nonatomic) NSTimeInterval updateInterval;
@property (nonatomic) double minDistanceFilter;
@property (nonatomic) BOOL enableSpeedAlerts;
@property (nonatomic) BOOL allowMockLocation;
@property (nonatomic) double speedThreshold;
@property (nonatomic, copy) NSString * _Nonnull accuracy;
@property (nonatomic) BOOL enableBackgroundMode;
@property (nonatomic) double distanceFilter;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, VMAuthMode, open) {
  VMAuthModeHeader = 0,
  VMAuthModeQueryParam = 1,
};

typedef SWIFT_ENUM(NSInteger, VMLocationMode, open) {
  VMLocationModeGpsCallback = 0,
  VMLocationModeExternalInput = 1,
};

typedef SWIFT_ENUM(NSInteger, VMVehicleType, open) {
  VMVehicleTypeCar = 1,
  VMVehicleTypeTaxi = 2,
  VMVehicleTypeBus = 3,
  VMVehicleTypeCoach = 4,
  VMVehicleTypeTruck = 5,
  VMVehicleTypeTrailer = 6,
  VMVehicleTypeCycle = 7,
  VMVehicleTypeBike = 8,
  VMVehicleTypePedestrian = 9,
  VMVehicleTypeSemiTrailer = 10,
};

@class NSDictionary;
/// Public Swift wrapper uses a name that does not collide with the module name.
/// The Swift name must stay distinct from the framework module name so the
/// generated <code>.swiftinterface</code> can qualify top-level symbols safely.
SWIFT_CLASS("_TtC18VietmapTrackingSDK15VietmapTracking")
@interface VietmapTracking : NSObject
/// Singleton instance
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) VietmapTracking * _Nonnull shared;)
+ (VietmapTracking * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)initializeWithApiKey:(NSString * _Nonnull)apiKey baseURL:(NSString * _Nonnull)baseURL;
- (void)configureWithApiKey:(NSString * _Nonnull)apiKey;
- (void)configureWithBaseURL:(NSString * _Nonnull)baseURL;
- (void)configureWithApiVersion:(NSString * _Nonnull)apiVersion;
- (void)setTrackingStatus:(NSString * _Nonnull)status;
- (void)configureWithApiKey:(NSString * _Nonnull)apiKey baseURL:(NSString * _Nonnull)baseURL autoUpload:(BOOL)autoUpload;
- (void)setMessagePackData:(NSDictionary * _Nullable)payload;
- (void)setAutoUploadWithEnabled:(BOOL)enabled;
- (NSDictionary * _Nullable)getCurrentLocation SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isTrackingActive SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary * _Nonnull)getTrackingStatus SWIFT_WARN_UNUSED_RESULT;
- (void)requestLocationPermissionsWithCompletion:(void (^ _Nonnull)(NSString * _Nonnull))completion;
- (void)requestAlwaysLocationPermissionsWithCompletion:(void (^ _Nonnull)(NSString * _Nonnull))completion;
- (BOOL)hasLocationPermissions SWIFT_WARN_UNUSED_RESULT;
- (void)startTrackingWithEnhancedBackgroundMode:(BOOL)enhancedBackgroundMode intervalMs:(NSInteger)intervalMs distanceFilter:(double)distanceFilter completion:(void (^ _Nonnull)(BOOL, NSString * _Nullable))completion;
- (void)stopTrackingWithCompletion:(void (^ _Nonnull)(BOOL, NSString * _Nullable))completion;
- (void)turnOnAlertWithCompletion:(void (^ _Nonnull)(BOOL))completion;
- (void)turnOffAlertWithCompletion:(void (^ _Nonnull)(BOOL))completion;
- (void)processExternalLocationWithLat:(double)lat lng:(double)lng speed:(double)speed heading:(double)heading;
- (void)processExternalLocation:(CLLocation * _Nonnull)location;
- (enum VMLocationMode)getCurrentLocationMode SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isSpeedAlertCurrentlyActive SWIFT_WARN_UNUSED_RESULT;
- (void)configureZoneNetworkV2WithBaseUrl:(NSString * _Nonnull)baseUrl;
- (void)resetZoneNetworkV2;
- (void)configureAlertAPIWithUrl:(NSString * _Nonnull)url apiKey:(NSString * _Nonnull)apiKey apiID:(NSString * _Nonnull)apiID;
- (NSInteger)getCachedLocationsCount SWIFT_WARN_UNUSED_RESULT;
- (void)uploadCachedLocationsManuallyWithCompletion:(void (^ _Nonnull)(BOOL, NSString * _Nullable))completion;
- (void)clearCachedLocations;
- (BOOL)isNetworkConnected SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary * _Nonnull)getTrackingHealthStatus SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) void (^ _Nullable onLocationUpdate)(NSDictionary * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onTrackingStatusChanged)(NSDictionary * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onError)(NSString * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onPermissionChanged)(NSString * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onRouteUpdate)(BOOL, NSDictionary * _Nullable);
- (void)startTrackingWithBackgroundMode:(BOOL)backgroundMode intervalMs:(NSInteger)intervalMs forceUpdateBackground:(BOOL)forceUpdateBackground distanceFilter:(double)distanceFilter completion:(void (^ _Nonnull)(BOOL, NSString * _Nullable))completion;
@end

SWIFT_CLASS("_TtC18VietmapTrackingSDK22VietmapTrackingManager")
@interface VietmapTrackingManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) VietmapTrackingManager * _Nonnull shared;)
+ (VietmapTrackingManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) void (^ _Nullable onLocationUpdate)(NSDictionary * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onTrackingStatusChanged)(NSDictionary * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onError)(NSString * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onPermissionChanged)(NSString * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onRouteUpdate)(BOOL, NSDictionary * _Nullable);
/// Fired when a fake/simulated GPS location is detected.
/// SDK chỉ fire callback — application layer quyết định cách xử lý.
/// Payload keys: “isFake” (Bool), “reason” (String), “lat”, “lng”, “timestamp”
@property (nonatomic, copy) void (^ _Nullable onFakeGPSDetected)(NSDictionary * _Nonnull);
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWithApiKey:(NSString * _Nullable)apiKey;
- (void)initializeWithApiKey:(NSString * _Nonnull)apiKey baseURL:(NSString * _Nonnull)baseURL;
- (void)configureWithApiKey:(NSString * _Nonnull)apiKey;
- (void)configureWithBaseURL:(NSString * _Nonnull)baseURL;
- (void)configureWithApiVersion:(NSString * _Nonnull)apiVersion;
- (void)setTrackingStatus:(NSString * _Nonnull)status;
- (void)configureWithApiKey:(NSString * _Nonnull)apiKey baseURL:(NSString * _Nonnull)baseURL autoUpload:(BOOL)autoUpload;
- (void)setAutoUploadWithEnabled:(BOOL)enabled;
- (void)configureWithAuthMode:(enum VMAuthMode)authMode;
- (void)configureWithConfig:(TrackingConfig * _Nonnull)config;
- (void)setVehicleId:(NSString * _Nonnull)vehicleId;
- (void)setDriverId:(NSString * _Nullable)driverId;
- (void)setMessagePackData:(NSDictionary * _Nullable)payload;
- (NSString * _Nullable)getVehicleId SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getDriverId SWIFT_WARN_UNUSED_RESULT;
- (void)onAppBackground;
- (void)onAppForeground;
- (NSDictionary * _Nullable)getCurrentLocation SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isTrackingActive SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary * _Nonnull)getTrackingStatus SWIFT_WARN_UNUSED_RESULT;
- (void)requestLocationPermissionsWithCompletion:(void (^ _Nonnull)(NSString * _Nonnull))completion;
- (void)requestAlwaysLocationPermissionsWithCompletion:(void (^ _Nonnull)(NSString * _Nonnull))completion;
- (BOOL)hasLocationPermissions SWIFT_WARN_UNUSED_RESULT;
- (void)startTrackingWithEnhancedBackgroundMode:(BOOL)enhancedBackgroundMode intervalMs:(NSInteger)intervalMs distanceFilter:(double)distanceFilter completion:(void (^ _Nonnull)(BOOL, NSString * _Nullable))completion;
- (void)stopTrackingWithCompletion:(void (^ _Nonnull)(BOOL, NSString * _Nullable))completion;
- (void)turnOnAlertWithCompletion:(void (^ _Nonnull)(BOOL))completion;
- (void)turnOffAlertWithCompletion:(void (^ _Nonnull)(BOOL))completion;
- (void)configureAlertAPIWithApiKey:(NSString * _Nonnull)apiKey apiID:(NSString * _Nonnull)apiID url:(NSString * _Nonnull)url;
/// Kích hoạt tích hợp GraphEngine v2 với Zone Network API.
/// Sau khi gọi hàm này, mỗi GPS update sẽ:
/// <ol>
///   <li>
///     Tự động fetch dữ liệu bản đồ từ Zone Network API (nếu cần)
///   </li>
///   <li>
///     Map-match vị trí GPS vào graph v2
///   </li>
///   <li>
///     Gọi <code>onGraphV2Result</code> với kết quả cảnh báo
///   </li>
/// </ol>
/// \param baseUrl Địa chỉ gốc API, ví dụ “http://192.168.10.165:5207”
///
- (void)configureZoneNetworkV2WithBaseUrl:(NSString * _Nonnull)baseUrl;
/// Xóa cache và reset engine v2 (dùng khi thay đổi vehicleType/seats/weights).
- (void)resetZoneNetworkV2;
/// Process location with vehicle type for speed alerts
/// @param lat Latitude coordinate
/// @param lng Longitude coordinate
/// @param speed Current speed in m/s
/// @param heading Current heading in degrees
/// @param vehicleId Unique identifier for the vehicle (default: 1)
/// @param vehicleType Type of vehicle using VMVehicleType enum (default: .car)
/// @param seats Number of seats in the vehicle (default: 5)
/// @param weights Vehicle weight in kg (default: 1500.0)
- (void)processLocationWithVehicleTypeLat:(double)lat lng:(double)lng speed:(double)speed heading:(double)heading vehicleId:(NSString * _Nonnull)vehicleId vehicleTypeEnum:(enum VMVehicleType)vehicleType seats:(NSInteger)seats weights:(double)weights;
/// Process location with custom vehicle parameters for speed alerts (backward compatibility)
/// @param lat Latitude coordinate
/// @param lng Longitude coordinate
/// @param speed Current speed in m/s
/// @param heading Current heading in degrees
/// @param vehicleId Unique identifier for the vehicle (default: 1)
/// @param vehicleType Type of vehicle - 1=Car, 2=Truck, etc. (default: 1)
/// @param seats Number of seats in the vehicle (default: 5)
/// @param weights Vehicle weight in kg (default: 1500.0)
- (void)processLocationWithVehicleParamsWithLat:(double)lat lng:(double)lng speed:(double)speed heading:(double)heading vehicleId:(NSString * _Nonnull)vehicleId vehicleType:(NSInteger)vehicleType seats:(NSInteger)seats weights:(double)weights;
/// Configure vehicle information for speed alerts (using VMVehicleType enum)
/// @param vehicleId Unique identifier for the vehicle
/// @param vehicleType Type of vehicle using VMVehicleType enum
/// @param seats Number of seats in the vehicle
/// @param weight Vehicle weight in kg
/// @param maxProvision Maximum provision value
- (void)configureVehicleWithVehicleId:(NSString * _Nonnull)vehicleId vehicleTypeEnum:(enum VMVehicleType)vehicleType seats:(NSInteger)seats weight:(double)weight;
/// Configure vehicle information for speed alerts (backward compatibility)
/// @param vehicleId Unique identifier for the vehicle
/// @param vehicleType Type of vehicle (1 = Car, 2 = Truck, etc.)
/// @param seats Number of seats in the vehicle
/// @param weight Vehicle weight in kg
/// @param maxProvision Maximum provision value
- (void)configureVehicleWithVehicleId:(NSString * _Nonnull)vehicleId vehicleType:(NSInteger)vehicleType seats:(NSInteger)seats weight:(double)weight maxProvision:(NSInteger)maxProvision;
/// Get current vehicle configuration
- (NSDictionary * _Nonnull)getVehicleConfiguration SWIFT_WARN_UNUSED_RESULT;
/// Enable or disable mock location tracking.
/// If false (default), mock locations are rejected/dropped based on fakeGPSPolicy.
/// If true, mock locations are treated as valid and uploaded normally.
- (void)setAllowMockLocation:(BOOL)allow;
/// Process external location input for speed alerts
/// This method allows feeding location data from external sources
/// Auto-switches from GPS to external input mode when called
/// @param speed Speed value (km/h preferred). Values ≤ 30 are treated as m/s and converted once.
- (void)processExternalLocationWithLat:(double)lat lng:(double)lng speed:(double)speed heading:(double)heading;
/// Process external location input with CLLocation object
/// Convenience method for existing CLLocation objects (speed usually in m/s)
- (void)processExternalLocation:(CLLocation * _Nonnull)location;
/// Get current location mode
- (enum VMLocationMode)getCurrentLocationMode SWIFT_WARN_UNUSED_RESULT;
/// Check if speed alerts are currently active
- (BOOL)isSpeedAlertCurrentlyActive SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getCachedLocationsCount SWIFT_WARN_UNUSED_RESULT;
- (void)uploadCachedLocationsManuallyWithCompletion:(void (^ _Nonnull)(BOOL, NSString * _Nullable))completion;
- (void)clearCachedLocations;
/// Configure database retention limits.
/// \param maxRecords max cached rows (0 = unlimited, default 10 000)
///
/// \param maxDbSizeBytes max database file size in bytes (0 = unlimited, default 50 MB)
///
/// \param batchSize rows per upload batch (default 50)
///
- (void)configureCacheLimitsWithMaxRecords:(NSInteger)maxRecords maxDbSizeBytes:(int64_t)maxDbSizeBytes batchSize:(NSInteger)batchSize;
/// Get current SQLite database file size in bytes.
- (int64_t)getDatabaseSizeBytes SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isNetworkConnected SWIFT_WARN_UNUSED_RESULT;
/// Fetch GPS tracking history from the server.
/// \param userId Driver/user ID to query
///
/// \param fromTime Start timestamp (Unix ms)
///
/// \param toTime End timestamp (Unix ms)
///
/// \param pageNumber 1-based page index
///
/// \param pageSize Records per page
///
/// \param sortBy Field to sort by (e.g. “timestamp”)
///
/// \param sortDescending Sort direction
///
/// \param completion (historyJson?, errorCode?, errorMessage?)
///
- (void)getHistoryWithUserId:(NSString * _Nonnull)userId fromTime:(int64_t)fromTime toTime:(int64_t)toTime pageNumber:(NSInteger)pageNumber pageSize:(NSInteger)pageSize sortBy:(NSString * _Nonnull)sortBy sortDescending:(BOOL)sortDescending completion:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSString * _Nullable))completion;
/// Force-refresh network status by restarting NWPathMonitor.
/// Per Apple docs, a cancelled NWPathMonitor cannot be restarted — must create new instance.
/// The new monitor’s pathUpdateHandler fires immediately with the current path,
/// updating isNetworkAvailable and triggering uploadPendingBatch if online.
- (void)refreshNetworkStatus;
/// Gets comprehensive tracking status for debugging
- (NSDictionary * _Nonnull)getTrackingHealthStatus SWIFT_WARN_UNUSED_RESULT;
/// Set the policy the SDK applies automatically whenever a fake GPS location is detected.
/// Call once during app initialisation (e.g. from Flutter layer).
/// \param policy one of “skip” | “warn” | “stopTracking” | “logToServer”
/// Invalid values are ignored and the policy falls back to “skip”.
///
- (void)setFakeGPSPolicy:(NSString * _Nonnull)policy;
@end

/// Speed status enum matching C++ SpeedStatus
typedef SWIFT_ENUM(NSInteger, SpeedStatus, open) {
  SpeedStatusSafe = 0,
  SpeedStatusNearLimit = 1,
  SpeedStatusOverLimit = 2,
};

@interface VietmapTrackingManager (SWIFT_EXTENSION(VietmapTrackingSDK))
- (void)startTrackingWithBackgroundMode:(BOOL)backgroundMode intervalMs:(NSInteger)intervalMs forceUpdateBackground:(BOOL)forceUpdateBackground distanceFilter:(double)distanceFilter completion:(void (^ _Nonnull)(BOOL, NSString * _Nullable))completion;
@end

SWIFT_AVAILABILITY(ios,introduced=14.0)
@interface VietmapTrackingManager (SWIFT_EXTENSION(VietmapTrackingSDK))
- (void)startEnhancedTrackingWithHighAccuracyMode:(BOOL)highAccuracyMode completion:(void (^ _Nonnull)(BOOL, NSString * _Nullable))completion SWIFT_AVAILABILITY(ios,introduced=14.0);
- (NSDictionary * _Nonnull)getEnhancedLocationStatus SWIFT_WARN_UNUSED_RESULT SWIFT_AVAILABILITY(ios,introduced=14.0);
- (void)requestFullLocationAccuracy;
@end

@interface VietmapTrackingManager (SWIFT_EXTENSION(VietmapTrackingSDK)) <CLLocationManagerDelegate>
- (void)locationManager:(CLLocationManager * _Nonnull)manager didUpdateLocations:(NSArray<CLLocation *> * _Nonnull)locations;
/// Process speed alert using C++ with custom vehicle parameters
/// @param location Current location data
/// @param vehicleId Unique identifier for the vehicle
/// @param vehicleType Type of vehicle (1 = Car, 2 = Truck, etc.)
/// @param seats Number of seats in the vehicle
/// @param weights Vehicle weight in kg
- (void)processSpeedAlertUsingCPPWithLocation:(CLLocation * _Nonnull)location vehicleId:(NSString * _Nonnull)vehicleId vehicleType:(NSInteger)vehicleType seats:(NSInteger)seats weights:(double)weights;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didFailWithError:(NSError * _Nonnull)error;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didChangeAuthorizationStatus:(CLAuthorizationStatus)status;
@end

/// ZoneNetworkManagerV2 — thin Swift wrapper around VietmapGraphBridgeV2.
/// All heavy work (HTTP fetch, base64/XOR decrypt, JSON parse, engine loading)
/// runs inside C++.  Swift only:
/// • schedules background execution
/// • delivers bitmaps to the UI  (via onBitmap closure)
/// • speaks voice (TTS) at the call site
SWIFT_CLASS("_TtC18VietmapTrackingSDK20ZoneNetworkManagerV2")
@interface ZoneNetworkManagerV2 : NSObject
/// Called on main thread when zone data is freshly loaded.
@property (nonatomic, copy) void (^ _Nullable onReady)(NSInteger, NSInteger);
- (nonnull instancetype)initWithBaseUrl:(NSString * _Nonnull)baseUrl vehicleType:(NSInteger)vehicleType seats:(NSInteger)seats weights:(NSInteger)weights OBJC_DESIGNATED_INITIALIZER;
/// Trigger a zone data reload if the position has moved outside the cached zone.
/// HTTP fetch + decrypt + parse + engine load all happen in C++ on a background
/// queue; Swift only schedules and reports back.
- (void)updateLocationWithLat:(double)lat lng:(double)lng;
/// Pass raw GPS to C++ for map-matching, alert scanning and bitmap generation.
/// @param speedKmh GPS speed in km/h
- (void)processGpsWithLat:(double)lat lng:(double)lng bearing:(double)bearing speedKmh:(double)speedKmh accuracy:(double)accuracy;
/// Reset C++ engine (use when vehicle params change).
- (void)reset;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.3 effective-5.10 (swiftlang-6.3.0.123.5 clang-2100.0.123.102)
#ifndef VIETMAPTRACKINGSDK_SWIFT_H
#define VIETMAPTRACKINGSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="VietmapTrackingSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreLocation;
@import Foundation;
@import ObjectiveC;
@import _LocationEssentials;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="VietmapTrackingSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class CLLocation;
@class NSString;
SWIFT_CLASS("_TtC18VietmapTrackingSDK23EnhancedLocationManager")
@interface EnhancedLocationManager : NSObject
@property (nonatomic, copy) void (^ _Nullable onLocationUpdate)(CLLocation * _Nonnull, NSString * _Nonnull, NSString * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onLocationError)(NSString * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onAuthorizationChanged)(CLAuthorizationStatus);
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)startTrackingWithHighAccuracyMode:(BOOL)highAccuracyMode SWIFT_AVAILABILITY(ios,introduced=14.0);
- (void)stopTracking;
- (void)requestLocationPermissions SWIFT_AVAILABILITY(ios,introduced=14.0);
- (BOOL)isTracking SWIFT_WARN_UNUSED_RESULT;
- (CLLocation * _Nullable)getLastKnownLocation SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getLocationServicesStatus SWIFT_WARN_UNUSED_RESULT SWIFT_AVAILABILITY(ios,introduced=14.0);
- (void)requestFullAccuracy;
- (void)setCustomAccuracy:(CLLocationAccuracy)accuracy distanceFilter:(CLLocationDistance)distanceFilter;
- (void)enableBackgroundLocationUpdates:(BOOL)enable SWIFT_AVAILABILITY(ios,introduced=14.0);
@end

@class CLLocationManager;
@interface EnhancedLocationManager (SWIFT_EXTENSION(VietmapTrackingSDK)) <CLLocationManagerDelegate>
- (void)locationManager:(CLLocationManager * _Nonnull)manager didUpdateLocations:(NSArray<CLLocation *> * _Nonnull)locations;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didFailWithError:(NSError * _Nonnull)error;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didChangeAuthorizationStatus:(CLAuthorizationStatus)status;
- (void)locationManagerDidChangeAuthorization:(CLLocationManager * _Nonnull)manager SWIFT_AVAILABILITY(ios,introduced=14.0);
@end

SWIFT_CLASS("_TtC18VietmapTrackingSDK14TrackingConfig")
@interface TrackingConfig : NSObject
@property (nonatomic) NSTimeInterval updateInterval;
@property (nonatomic) double minDistanceFilter;
@property (nonatomic) BOOL enableSpeedAlerts;
@property (nonatomic) BOOL allowMockLocation;
@property (nonatomic) double speedThreshold;
@property (nonatomic, copy) NSString * _Nonnull accuracy;
@property (nonatomic) BOOL enableBackgroundMode;
@property (nonatomic) double distanceFilter;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, VMAuthMode, open) {
  VMAuthModeHeader = 0,
  VMAuthModeQueryParam = 1,
};

typedef SWIFT_ENUM(NSInteger, VMLocationMode, open) {
  VMLocationModeGpsCallback = 0,
  VMLocationModeExternalInput = 1,
};

typedef SWIFT_ENUM(NSInteger, VMVehicleType, open) {
  VMVehicleTypeCar = 1,
  VMVehicleTypeTaxi = 2,
  VMVehicleTypeBus = 3,
  VMVehicleTypeCoach = 4,
  VMVehicleTypeTruck = 5,
  VMVehicleTypeTrailer = 6,
  VMVehicleTypeCycle = 7,
  VMVehicleTypeBike = 8,
  VMVehicleTypePedestrian = 9,
  VMVehicleTypeSemiTrailer = 10,
};

@class NSDictionary;
/// Public Swift wrapper uses a name that does not collide with the module name.
/// The Swift name must stay distinct from the framework module name so the
/// generated <code>.swiftinterface</code> can qualify top-level symbols safely.
SWIFT_CLASS("_TtC18VietmapTrackingSDK15VietmapTracking")
@interface VietmapTracking : NSObject
/// Singleton instance
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) VietmapTracking * _Nonnull shared;)
+ (VietmapTracking * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)initializeWithApiKey:(NSString * _Nonnull)apiKey baseURL:(NSString * _Nonnull)baseURL;
- (void)configureWithApiKey:(NSString * _Nonnull)apiKey;
- (void)configureWithBaseURL:(NSString * _Nonnull)baseURL;
- (void)configureWithApiVersion:(NSString * _Nonnull)apiVersion;
- (void)setTrackingStatus:(NSString * _Nonnull)status;
- (void)configureWithApiKey:(NSString * _Nonnull)apiKey baseURL:(NSString * _Nonnull)baseURL autoUpload:(BOOL)autoUpload;
- (void)setMessagePackData:(NSDictionary * _Nullable)payload;
- (void)setAutoUploadWithEnabled:(BOOL)enabled;
- (NSDictionary * _Nullable)getCurrentLocation SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isTrackingActive SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary * _Nonnull)getTrackingStatus SWIFT_WARN_UNUSED_RESULT;
- (void)requestLocationPermissionsWithCompletion:(void (^ _Nonnull)(NSString * _Nonnull))completion;
- (void)requestAlwaysLocationPermissionsWithCompletion:(void (^ _Nonnull)(NSString * _Nonnull))completion;
- (BOOL)hasLocationPermissions SWIFT_WARN_UNUSED_RESULT;
- (void)startTrackingWithEnhancedBackgroundMode:(BOOL)enhancedBackgroundMode intervalMs:(NSInteger)intervalMs distanceFilter:(double)distanceFilter completion:(void (^ _Nonnull)(BOOL, NSString * _Nullable))completion;
- (void)stopTrackingWithCompletion:(void (^ _Nonnull)(BOOL, NSString * _Nullable))completion;
- (void)turnOnAlertWithCompletion:(void (^ _Nonnull)(BOOL))completion;
- (void)turnOffAlertWithCompletion:(void (^ _Nonnull)(BOOL))completion;
- (void)processExternalLocationWithLat:(double)lat lng:(double)lng speed:(double)speed heading:(double)heading;
- (void)processExternalLocation:(CLLocation * _Nonnull)location;
- (enum VMLocationMode)getCurrentLocationMode SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isSpeedAlertCurrentlyActive SWIFT_WARN_UNUSED_RESULT;
- (void)configureZoneNetworkV2WithBaseUrl:(NSString * _Nonnull)baseUrl;
- (void)resetZoneNetworkV2;
- (void)configureAlertAPIWithUrl:(NSString * _Nonnull)url apiKey:(NSString * _Nonnull)apiKey apiID:(NSString * _Nonnull)apiID;
- (NSInteger)getCachedLocationsCount SWIFT_WARN_UNUSED_RESULT;
- (void)uploadCachedLocationsManuallyWithCompletion:(void (^ _Nonnull)(BOOL, NSString * _Nullable))completion;
- (void)clearCachedLocations;
- (BOOL)isNetworkConnected SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary * _Nonnull)getTrackingHealthStatus SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) void (^ _Nullable onLocationUpdate)(NSDictionary * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onTrackingStatusChanged)(NSDictionary * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onError)(NSString * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onPermissionChanged)(NSString * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onRouteUpdate)(BOOL, NSDictionary * _Nullable);
- (void)startTrackingWithBackgroundMode:(BOOL)backgroundMode intervalMs:(NSInteger)intervalMs forceUpdateBackground:(BOOL)forceUpdateBackground distanceFilter:(double)distanceFilter completion:(void (^ _Nonnull)(BOOL, NSString * _Nullable))completion;
@end

SWIFT_CLASS("_TtC18VietmapTrackingSDK22VietmapTrackingManager")
@interface VietmapTrackingManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) VietmapTrackingManager * _Nonnull shared;)
+ (VietmapTrackingManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) void (^ _Nullable onLocationUpdate)(NSDictionary * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onTrackingStatusChanged)(NSDictionary * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onError)(NSString * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onPermissionChanged)(NSString * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onRouteUpdate)(BOOL, NSDictionary * _Nullable);
/// Fired when a fake/simulated GPS location is detected.
/// SDK chỉ fire callback — application layer quyết định cách xử lý.
/// Payload keys: “isFake” (Bool), “reason” (String), “lat”, “lng”, “timestamp”
@property (nonatomic, copy) void (^ _Nullable onFakeGPSDetected)(NSDictionary * _Nonnull);
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWithApiKey:(NSString * _Nullable)apiKey;
- (void)initializeWithApiKey:(NSString * _Nonnull)apiKey baseURL:(NSString * _Nonnull)baseURL;
- (void)configureWithApiKey:(NSString * _Nonnull)apiKey;
- (void)configureWithBaseURL:(NSString * _Nonnull)baseURL;
- (void)configureWithApiVersion:(NSString * _Nonnull)apiVersion;
- (void)setTrackingStatus:(NSString * _Nonnull)status;
- (void)configureWithApiKey:(NSString * _Nonnull)apiKey baseURL:(NSString * _Nonnull)baseURL autoUpload:(BOOL)autoUpload;
- (void)setAutoUploadWithEnabled:(BOOL)enabled;
- (void)configureWithAuthMode:(enum VMAuthMode)authMode;
- (void)configureWithConfig:(TrackingConfig * _Nonnull)config;
- (void)setVehicleId:(NSString * _Nonnull)vehicleId;
- (void)setDriverId:(NSString * _Nullable)driverId;
- (void)setMessagePackData:(NSDictionary * _Nullable)payload;
- (NSString * _Nullable)getVehicleId SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getDriverId SWIFT_WARN_UNUSED_RESULT;
- (void)onAppBackground;
- (void)onAppForeground;
- (NSDictionary * _Nullable)getCurrentLocation SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isTrackingActive SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary * _Nonnull)getTrackingStatus SWIFT_WARN_UNUSED_RESULT;
- (void)requestLocationPermissionsWithCompletion:(void (^ _Nonnull)(NSString * _Nonnull))completion;
- (void)requestAlwaysLocationPermissionsWithCompletion:(void (^ _Nonnull)(NSString * _Nonnull))completion;
- (BOOL)hasLocationPermissions SWIFT_WARN_UNUSED_RESULT;
- (void)startTrackingWithEnhancedBackgroundMode:(BOOL)enhancedBackgroundMode intervalMs:(NSInteger)intervalMs distanceFilter:(double)distanceFilter completion:(void (^ _Nonnull)(BOOL, NSString * _Nullable))completion;
- (void)stopTrackingWithCompletion:(void (^ _Nonnull)(BOOL, NSString * _Nullable))completion;
- (void)turnOnAlertWithCompletion:(void (^ _Nonnull)(BOOL))completion;
- (void)turnOffAlertWithCompletion:(void (^ _Nonnull)(BOOL))completion;
- (void)configureAlertAPIWithApiKey:(NSString * _Nonnull)apiKey apiID:(NSString * _Nonnull)apiID url:(NSString * _Nonnull)url;
/// Kích hoạt tích hợp GraphEngine v2 với Zone Network API.
/// Sau khi gọi hàm này, mỗi GPS update sẽ:
/// <ol>
///   <li>
///     Tự động fetch dữ liệu bản đồ từ Zone Network API (nếu cần)
///   </li>
///   <li>
///     Map-match vị trí GPS vào graph v2
///   </li>
///   <li>
///     Gọi <code>onGraphV2Result</code> với kết quả cảnh báo
///   </li>
/// </ol>
/// \param baseUrl Địa chỉ gốc API, ví dụ “http://192.168.10.165:5207”
///
- (void)configureZoneNetworkV2WithBaseUrl:(NSString * _Nonnull)baseUrl;
/// Xóa cache và reset engine v2 (dùng khi thay đổi vehicleType/seats/weights).
- (void)resetZoneNetworkV2;
/// Process location with vehicle type for speed alerts
/// @param lat Latitude coordinate
/// @param lng Longitude coordinate
/// @param speed Current speed in m/s
/// @param heading Current heading in degrees
/// @param vehicleId Unique identifier for the vehicle (default: 1)
/// @param vehicleType Type of vehicle using VMVehicleType enum (default: .car)
/// @param seats Number of seats in the vehicle (default: 5)
/// @param weights Vehicle weight in kg (default: 1500.0)
- (void)processLocationWithVehicleTypeLat:(double)lat lng:(double)lng speed:(double)speed heading:(double)heading vehicleId:(NSString * _Nonnull)vehicleId vehicleTypeEnum:(enum VMVehicleType)vehicleType seats:(NSInteger)seats weights:(double)weights;
/// Process location with custom vehicle parameters for speed alerts (backward compatibility)
/// @param lat Latitude coordinate
/// @param lng Longitude coordinate
/// @param speed Current speed in m/s
/// @param heading Current heading in degrees
/// @param vehicleId Unique identifier for the vehicle (default: 1)
/// @param vehicleType Type of vehicle - 1=Car, 2=Truck, etc. (default: 1)
/// @param seats Number of seats in the vehicle (default: 5)
/// @param weights Vehicle weight in kg (default: 1500.0)
- (void)processLocationWithVehicleParamsWithLat:(double)lat lng:(double)lng speed:(double)speed heading:(double)heading vehicleId:(NSString * _Nonnull)vehicleId vehicleType:(NSInteger)vehicleType seats:(NSInteger)seats weights:(double)weights;
/// Configure vehicle information for speed alerts (using VMVehicleType enum)
/// @param vehicleId Unique identifier for the vehicle
/// @param vehicleType Type of vehicle using VMVehicleType enum
/// @param seats Number of seats in the vehicle
/// @param weight Vehicle weight in kg
/// @param maxProvision Maximum provision value
- (void)configureVehicleWithVehicleId:(NSString * _Nonnull)vehicleId vehicleTypeEnum:(enum VMVehicleType)vehicleType seats:(NSInteger)seats weight:(double)weight;
/// Configure vehicle information for speed alerts (backward compatibility)
/// @param vehicleId Unique identifier for the vehicle
/// @param vehicleType Type of vehicle (1 = Car, 2 = Truck, etc.)
/// @param seats Number of seats in the vehicle
/// @param weight Vehicle weight in kg
/// @param maxProvision Maximum provision value
- (void)configureVehicleWithVehicleId:(NSString * _Nonnull)vehicleId vehicleType:(NSInteger)vehicleType seats:(NSInteger)seats weight:(double)weight maxProvision:(NSInteger)maxProvision;
/// Get current vehicle configuration
- (NSDictionary * _Nonnull)getVehicleConfiguration SWIFT_WARN_UNUSED_RESULT;
/// Enable or disable mock location tracking.
/// If false (default), mock locations are rejected/dropped based on fakeGPSPolicy.
/// If true, mock locations are treated as valid and uploaded normally.
- (void)setAllowMockLocation:(BOOL)allow;
/// Process external location input for speed alerts
/// This method allows feeding location data from external sources
/// Auto-switches from GPS to external input mode when called
/// @param speed Speed value (km/h preferred). Values ≤ 30 are treated as m/s and converted once.
- (void)processExternalLocationWithLat:(double)lat lng:(double)lng speed:(double)speed heading:(double)heading;
/// Process external location input with CLLocation object
/// Convenience method for existing CLLocation objects (speed usually in m/s)
- (void)processExternalLocation:(CLLocation * _Nonnull)location;
/// Get current location mode
- (enum VMLocationMode)getCurrentLocationMode SWIFT_WARN_UNUSED_RESULT;
/// Check if speed alerts are currently active
- (BOOL)isSpeedAlertCurrentlyActive SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getCachedLocationsCount SWIFT_WARN_UNUSED_RESULT;
- (void)uploadCachedLocationsManuallyWithCompletion:(void (^ _Nonnull)(BOOL, NSString * _Nullable))completion;
- (void)clearCachedLocations;
/// Configure database retention limits.
/// \param maxRecords max cached rows (0 = unlimited, default 10 000)
///
/// \param maxDbSizeBytes max database file size in bytes (0 = unlimited, default 50 MB)
///
/// \param batchSize rows per upload batch (default 50)
///
- (void)configureCacheLimitsWithMaxRecords:(NSInteger)maxRecords maxDbSizeBytes:(int64_t)maxDbSizeBytes batchSize:(NSInteger)batchSize;
/// Get current SQLite database file size in bytes.
- (int64_t)getDatabaseSizeBytes SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isNetworkConnected SWIFT_WARN_UNUSED_RESULT;
/// Fetch GPS tracking history from the server.
/// \param userId Driver/user ID to query
///
/// \param fromTime Start timestamp (Unix ms)
///
/// \param toTime End timestamp (Unix ms)
///
/// \param pageNumber 1-based page index
///
/// \param pageSize Records per page
///
/// \param sortBy Field to sort by (e.g. “timestamp”)
///
/// \param sortDescending Sort direction
///
/// \param completion (historyJson?, errorCode?, errorMessage?)
///
- (void)getHistoryWithUserId:(NSString * _Nonnull)userId fromTime:(int64_t)fromTime toTime:(int64_t)toTime pageNumber:(NSInteger)pageNumber pageSize:(NSInteger)pageSize sortBy:(NSString * _Nonnull)sortBy sortDescending:(BOOL)sortDescending completion:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSString * _Nullable))completion;
/// Force-refresh network status by restarting NWPathMonitor.
/// Per Apple docs, a cancelled NWPathMonitor cannot be restarted — must create new instance.
/// The new monitor’s pathUpdateHandler fires immediately with the current path,
/// updating isNetworkAvailable and triggering uploadPendingBatch if online.
- (void)refreshNetworkStatus;
/// Gets comprehensive tracking status for debugging
- (NSDictionary * _Nonnull)getTrackingHealthStatus SWIFT_WARN_UNUSED_RESULT;
/// Set the policy the SDK applies automatically whenever a fake GPS location is detected.
/// Call once during app initialisation (e.g. from Flutter layer).
/// \param policy one of “skip” | “warn” | “stopTracking” | “logToServer”
/// Invalid values are ignored and the policy falls back to “skip”.
///
- (void)setFakeGPSPolicy:(NSString * _Nonnull)policy;
@end

/// Speed status enum matching C++ SpeedStatus
typedef SWIFT_ENUM(NSInteger, SpeedStatus, open) {
  SpeedStatusSafe = 0,
  SpeedStatusNearLimit = 1,
  SpeedStatusOverLimit = 2,
};

@interface VietmapTrackingManager (SWIFT_EXTENSION(VietmapTrackingSDK))
- (void)startTrackingWithBackgroundMode:(BOOL)backgroundMode intervalMs:(NSInteger)intervalMs forceUpdateBackground:(BOOL)forceUpdateBackground distanceFilter:(double)distanceFilter completion:(void (^ _Nonnull)(BOOL, NSString * _Nullable))completion;
@end

SWIFT_AVAILABILITY(ios,introduced=14.0)
@interface VietmapTrackingManager (SWIFT_EXTENSION(VietmapTrackingSDK))
- (void)startEnhancedTrackingWithHighAccuracyMode:(BOOL)highAccuracyMode completion:(void (^ _Nonnull)(BOOL, NSString * _Nullable))completion SWIFT_AVAILABILITY(ios,introduced=14.0);
- (NSDictionary * _Nonnull)getEnhancedLocationStatus SWIFT_WARN_UNUSED_RESULT SWIFT_AVAILABILITY(ios,introduced=14.0);
- (void)requestFullLocationAccuracy;
@end

@interface VietmapTrackingManager (SWIFT_EXTENSION(VietmapTrackingSDK)) <CLLocationManagerDelegate>
- (void)locationManager:(CLLocationManager * _Nonnull)manager didUpdateLocations:(NSArray<CLLocation *> * _Nonnull)locations;
/// Process speed alert using C++ with custom vehicle parameters
/// @param location Current location data
/// @param vehicleId Unique identifier for the vehicle
/// @param vehicleType Type of vehicle (1 = Car, 2 = Truck, etc.)
/// @param seats Number of seats in the vehicle
/// @param weights Vehicle weight in kg
- (void)processSpeedAlertUsingCPPWithLocation:(CLLocation * _Nonnull)location vehicleId:(NSString * _Nonnull)vehicleId vehicleType:(NSInteger)vehicleType seats:(NSInteger)seats weights:(double)weights;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didFailWithError:(NSError * _Nonnull)error;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didChangeAuthorizationStatus:(CLAuthorizationStatus)status;
@end

/// ZoneNetworkManagerV2 — thin Swift wrapper around VietmapGraphBridgeV2.
/// All heavy work (HTTP fetch, base64/XOR decrypt, JSON parse, engine loading)
/// runs inside C++.  Swift only:
/// • schedules background execution
/// • delivers bitmaps to the UI  (via onBitmap closure)
/// • speaks voice (TTS) at the call site
SWIFT_CLASS("_TtC18VietmapTrackingSDK20ZoneNetworkManagerV2")
@interface ZoneNetworkManagerV2 : NSObject
/// Called on main thread when zone data is freshly loaded.
@property (nonatomic, copy) void (^ _Nullable onReady)(NSInteger, NSInteger);
- (nonnull instancetype)initWithBaseUrl:(NSString * _Nonnull)baseUrl vehicleType:(NSInteger)vehicleType seats:(NSInteger)seats weights:(NSInteger)weights OBJC_DESIGNATED_INITIALIZER;
/// Trigger a zone data reload if the position has moved outside the cached zone.
/// HTTP fetch + decrypt + parse + engine load all happen in C++ on a background
/// queue; Swift only schedules and reports back.
- (void)updateLocationWithLat:(double)lat lng:(double)lng;
/// Pass raw GPS to C++ for map-matching, alert scanning and bitmap generation.
/// @param speedKmh GPS speed in km/h
- (void)processGpsWithLat:(double)lat lng:(double)lng bearing:(double)bearing speedKmh:(double)speedKmh accuracy:(double)accuracy;
/// Reset C++ engine (use when vehicle params change).
- (void)reset;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
